config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :customers
  resources :producers
  resources :products

  resources :sessions, only: [ :new, :create, :destroy ] 
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  get 'static_pages/home'
  root 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   Internal Applicaton for <a href="http://www.apexfoodcompany.com">Apex Food Company
  </small>
  <nav>
    <ul>
      <li><%= link_to "About" , '#'%></li>
      <% if current_user && current_user.admin? %>
        <li><%= link_to "Admin" , user_path(current_user) %></li>
      <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "afc", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if signed_in? %>
         <li><%= link_to "#{current_user.name}", edit_user_path(current_user) %></li>
         <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
        <% else %>
         <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>

</body>

</html>